// Generated by CoffeeScript 1.8.0
(function() {

  var Decoder, debug, encodeHelper, logger, util;

  util = require('util');

  debug = require('debug');

  encodeHelper = require('./common').encodeHelper;

  logger = debug('nodermi:decode');

  Decoder = (function() {
    function Decoder(server, source) {
      var _ref;
      this.server = server;
      this.source = source;
      _ref = this.server, this.host = _ref.host, this.port = _ref.port, this.objectRegistry = _ref.objectRegistry;
      this.decoded = {};
    }

    Decoder.prototype.decode = function(obj) {
      return this._decode(obj);
    };

    Decoder.prototype._decode = function(obj) {
      var i, id, remoteType, result, _i, _len;
      if ((obj == null) || (typeof obj !== 'object' && typeof obj !== 'function')) {
        return obj;
      }
      if (util.isArray(obj)) {
        result = [];
        for (_i = 0, _len = obj.length; _i < _len; _i++) {
          i = obj[_i];
          result.push(this._decode(i));
        }
        return result;
      }
      id = encodeHelper.getRid(obj);
      // it is from here
      if (encodeHelper.isOriginEquals(obj, 1)) {
        result = this.objectRegistry.getObject(id);
        if (result == null) {
          logger("cannot find object " + id);
        }
        this._markDecoded(obj, result);
        return result;
      }
      remoteType = encodeHelper.getFullRemoteType(obj);
      switch (remoteType) {
        case 'funcDes':
          return this._decodeFunction(obj);
        case 'arrDes':
          return this._decodeArray(obj);
        case 'dateDes':
          return this._decodeDate(obj);
        case 'pojo':
          return this._decodePojo(obj);
        case 'ref':
          return this._decodeRef(obj);
        default:
          return this._decodeObj(obj);
      }
    };

    Decoder.prototype._markDecoded = function(objDesc, result) {
      var remoteHost, remotePort;
      if (encodeHelper.isOriginEquals(objDesc, 1)) {
        // it is from myself
        this._markDecoded2(this.host, this.port, encodeHelper.getRid(objDesc), result);
        return;
      }
      remoteHost = encodeHelper.getHiddenRhost(result);
      remotePort = encodeHelper.getHiddenRport(result);
      return this._markDecoded2(remoteHost, remotePort, encodeHelper.getRid(objDesc), result);
    };

    Decoder.prototype._markDecoded2 = function(host, port, id, result) {
      if (this.decoded[host] == null) {
        this.decoded[host] = {};
      }
      if (this.decoded[host][port] == null) {
        this.decoded[host][port] = {};
      }
      return this.decoded[host][port][id] = result;
    };

    Decoder.prototype._decodeFunction = function(obj) {
      var func, funcId, server, source;
      source = this._getSource(obj);
      server = this.server;
      funcId = encodeHelper.getRid(obj);
      func = (function(source, funcId, server) {
        return function() {
          var thisObj = null;
          // pass this if it is from source
          if (this!=null && encodeHelper.getHiddenRhost(this) == source.host 
            && encodeHelper.getHiddenRport(this) == source.port) {
            thisObj = encodeHelper.getHiddenRid(this);
          }
          return server._invokeRemoteFunc(source, funcId, thisObj, arguments);
        };
      })(source, funcId, server);
      this._setRmiField(func, obj);
      this._markDecoded(obj, func);
      return func;
    };

    Decoder.prototype._getSource = function(obj) {
      var remoteHost, remotePort, source;
      remoteHost = encodeHelper.getRhost(obj);
      remotePort = encodeHelper.getRport(obj);
      source = null;
      if ((remoteHost == null) && (remotePort == null)) {
        source = this.source;
      } else {
        source = {
          host: remoteHost,
          port: remotePort
        };
      }
      return source;
    };

    Decoder.prototype._decodeArray = function(obj) {
      var arrayElements, i, result, _i, _len;
      result = [];
      this._setRmiField(result, obj);
      this._markDecoded(obj, result);
      arrayElements = encodeHelper.getArrayElements(obj);
      if (arrayElements != null) {
        for (_i = 0, _len = arrayElements.length; _i < _len; _i++) {
          i = arrayElements[_i];
          result.push(this._decode(i));
        }
      }
      return result;
    };

    // fill rmi id, host, etc to the stub object
    Decoder.prototype._setRmiField = function(stubObj, objDesc) {
      var remoteHost, remotePort;
      encodeHelper.setHiddenRid(stubObj, encodeHelper.getRid(objDesc));
      remoteHost = encodeHelper.getRhost(objDesc);
      remotePort = encodeHelper.getRport(objDesc);
      if ((remoteHost == null) && (remotePort == null)) {
        remoteHost = this.source.host;
        remotePort = this.source.port;
      }
      encodeHelper.setHiddenRhost(stubObj, remoteHost);
      return encodeHelper.setHiddenRport(stubObj, remotePort);
    };

    Decoder.prototype._decodeDate = function(obj) {
      var result, time;
      time = encodeHelper.getDateValue(obj);
      result = new Date(time);
      return result;
    };

    Decoder.prototype._decodePojo = function(obj) {
      return encodeHelper.getProperties(obj);
    };

    Decoder.prototype._decodeObj = function(obj) {
      var func, funcName, functions, k, objId, properties, result, server, source, v, _i, _len;
      result = {};
      this._setRmiField(result, obj);
      this._markDecoded(obj, result);
      properties = encodeHelper.getProperties(obj);
      if (properties != null) {
        for (k in properties) {
          v = properties[k];
          result[k] = this._decode(v, obj);
        }
      }
      return result;
    };

    Decoder.prototype._decodeRef = function(objDesc) {
      var id, remoteHost, remotePort, _ref, _ref1;
      id = encodeHelper.getRid(objDesc);
      remoteHost = encodeHelper.getRhost(objDesc);
      remotePort = encodeHelper.getRport(objDesc);
      if ((remoteHost == null) && (remotePort == null)) {
        remoteHost = this.source.host;
        remotePort = this.source.port;
      }
      return (_ref = this.decoded[remoteHost]) != null ? (_ref1 = _ref[remotePort]) != null ? _ref1[id] : void 0 : void 0;
    };

    return Decoder;

  })();

  module.exports = Decoder;

}).call(this);
