// Generated by CoffeeScript 1.8.0
(function() {
  var FileLogger, fs;

  fs = require('fs');

  FileLogger = (function() {
    function FileLogger(server) {
      var host, port, _ref;
      this.server = server;
      _ref = this.server, host = _ref.host, port = _ref.port, this.debug = _ref.debug;
      this.fileName = "nodermi_" + host + "_" + port + ".log";
      if (!this.debug) {
        this.enabled = false;
        this.log = function() {};
      } else {
        this.enabled = true;
      }
    }

    FileLogger.prototype.log = function(message) {
      var str;
      str = (new Date()).toString() + " : " + message + "\n";
      return fs.appendFile(this.fileName, str, function(err) {
        if (err) {
          console.log("nodermi logging error");
          console.log(err);
          return console.log(err.stack);
        }
      });
    };

    return FileLogger;

  })();

  module.exports = FileLogger;

}).call(this);
