// Generated by CoffeeScript 1.8.0
(function() {
  var ObjectRegistry, encodeHelper, weak;

  weak = require('weak');

  encodeHelper = require('./common').encodeHelper;

  ObjectRegistry = (function() {
    function ObjectRegistry() {
      this.objects = {};
      this.functions = {};
      this.sequence = 0;
    }

    ObjectRegistry.prototype.registObject = function(obj) {
      var id;
      if (encodeHelper.getHiddenRid(obj) == null) {
        id = this.getSequence();
        encodeHelper.setHiddenRid(obj, id);
        if (typeof obj === 'function') {
          return this.functions[id] = obj;
        } else {
          return this.objects[id] = weak(obj);
        }
      }
    };

    ObjectRegistry.prototype.getSequence = function() {
      var id;
      id = this.sequence.toString(35);
      this.sequence++;
      return id;
    };

    ObjectRegistry.prototype.getObject = function(id) {
      var func, val;
      func = this.functions[id];
      if (func != null) {
        return func;
      }
      val = this.objects[id];
      if (val == null) {
        delete this.objects[id];
      }
      return val;
    };

    return ObjectRegistry;

  })();

  module.exports = ObjectRegistry;

}).call(this);
